-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================
-- AUTHENTICATION INTEGRATION
-- ============================================
-- This schema integrates with Supabase Auth.
-- The users.id should match auth.users.id for RLS policies to work correctly.
-- When a user signs up via Google OAuth:
--   1. Supabase Auth creates entry in auth.users
--   2. Trigger/function creates corresponding entry in public.users
--   3. RLS policies use auth.uid() which returns authenticated user's UUID
-- ============================================

-- Users table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255),
    avatar_url TEXT,
    google_id VARCHAR(255) UNIQUE, -- OAuth provider ID from Google (renamed from provider_id for clarity)
    removed_at TIMESTAMP WITH TIME ZONE, -- Soft delete support for users
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Clothes table
-- NOTES:
--   - image_url: Full resolution image from Cloudinary (max 1080px after client-side resize)
--   - thumbnail_url: Auto-generated by Cloudinary transformations (e.g., c_thumb,w_300,h_300)
--   - removed_at: Soft delete field, items recoverable for 30 days
CREATE TABLE clothes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(50) CHECK (category IN ('top', 'bottom', 'outerwear', 'shoes', 'accessory')),
    image_url TEXT NOT NULL,
    thumbnail_url TEXT, -- Auto-generated thumbnail URL (Cloudinary transformation)
    style_tags TEXT[],
    privacy VARCHAR(20) DEFAULT 'friends' CHECK (privacy IN ('private', 'friends')),
    size VARCHAR(20),
    brand VARCHAR(100),
    removed_at TIMESTAMP WITH TIME ZONE, -- Soft delete: items retained for 30-day recovery period
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Friends table
CREATE TABLE friends (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('pending', 'accepted', 'rejected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(requester_id, receiver_id),
  CHECK (requester_id < receiver_id) -- Enforce canonical ordering to prevent duplicate friendships
);

-- Suggestions table
CREATE TABLE suggestions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  from_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  to_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  suggested_item_ids UUID[] NOT NULL,
  message TEXT CHECK (char_length(message) <= 100), -- Max 100 chars as per API spec
  is_read BOOLEAN DEFAULT false,
  viewed_at TIMESTAMP WITH TIME ZONE, -- Track when suggestion was read
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  CONSTRAINT check_item_ids_not_empty CHECK (array_length(suggested_item_ids, 1) > 0),
  CONSTRAINT check_max_items CHECK (array_length(suggested_item_ids, 1) <= 10) -- Max 10 items per suggestion
);

-- Future feature: likes/reactions
-- MOVED TO FUTURE MIGRATION: This table is not part of MVP
-- Uncomment and migrate when implementing likes feature
-- CREATE TABLE likes (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
--   item_id UUID NOT NULL REFERENCES clothes(id) ON DELETE CASCADE,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
--   UNIQUE(user_id, item_id)
-- );

-- ============================================
-- TRIGGERS: Automatic updated_at management
-- ============================================

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to all tables
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_clothes_updated_at
    BEFORE UPDATE ON clothes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_friends_updated_at
    BEFORE UPDATE ON friends
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_suggestions_updated_at
    BEFORE UPDATE ON suggestions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();