# StyleSnap - Manual Deployment Workflow
# Manually trigger builds, tests, or maintenance tasks

name: Manual Operations

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to perform'
        required: true
        type: choice
        options:
          - 'build-only'
          - 'test-only'
          - 'full-ci'
          - 'purge-old-items'
          - 'cloudinary-cleanup'
      environment:
        description: 'Environment'
        required: true
        type: choice
        default: 'staging'
        options:
          - 'staging'
          - 'production'

jobs:
  manual-operation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run selected operation
      run: |
        case "${{ inputs.operation }}" in
          "build-only")
            echo "Building for ${{ inputs.environment }}..."
            npm run build
            ;;
          "test-only")
            echo "Running tests..."
            if npm run test --dry-run 2>/dev/null; then
              npm test
            else
              echo "No tests configured yet, skipping..."
            fi
            ;;
          "full-ci")
            echo "Running full CI pipeline..."
            npm run lint
            npm run build
            if npm run test --dry-run 2>/dev/null; then
              npm test
            else
              echo "No tests configured yet, skipping..."
            fi
            ;;
          "purge-old-items")
            echo "⚠️  Running purge-old-items script (DRY RUN)..."
            if npm run purge-old-items --dry-run 2>/dev/null; then
              npm run purge-old-items -- --dry-run
            else
              echo "Purge script not implemented yet"
            fi
            ;;
          "cloudinary-cleanup")
            echo "⚠️  Running cloudinary-cleanup script (DRY RUN)..."
            if npm run cloudinary-cleanup --dry-run 2>/dev/null; then
              npm run cloudinary-cleanup -- --dry-run
            else
              echo "Cloudinary cleanup script not implemented yet"
            fi
            ;;
        esac
      env:
        NODE_ENV: ${{ inputs.environment }}
    
    - name: Operation completed
      run: echo "✅ Operation '${{ inputs.operation }}' completed for ${{ inputs.environment }}"
