name: Summarize new issues

on:
  issues:
    types: [opened]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate issue summary
        run: |
          # Create a simple summary based on issue content
          TITLE="${{ github.event.issue.title }}"
          BODY="${{ github.event.issue.body }}"
          
          # Extract key information
          SUMMARY="📋 **Issue Summary**\n\n"
          SUMMARY+="**Title:** $TITLE\n\n"
          
          # Check if it's a bug report
          if echo "$BODY" | grep -qi "bug\|error\|issue\|problem\|broken"; then
            SUMMARY+="🏷️ **Type:** Bug Report\n\n"
          elif echo "$BODY" | grep -qi "feature\|enhancement\|improvement\|add"; then
            SUMMARY+="🏷️ **Type:** Feature Request\n\n"
          elif echo "$BODY" | grep -qi "question\|help\|how\|what"; then
            SUMMARY+="🏷️ **Type:** Question\n\n"
          else
            SUMMARY+="🏷️ **Type:** General Issue\n\n"
          fi
          
          # Add priority based on labels
          if echo "$BODY" | grep -qi "urgent\|critical\|asap\|emergency"; then
            SUMMARY+="⚡ **Priority:** High\n\n"
          elif echo "$BODY" | grep -qi "low\|minor\|nice to have"; then
            SUMMARY+="⚡ **Priority:** Low\n\n"
          else
            SUMMARY+="⚡ **Priority:** Medium\n\n"
          fi
          
          SUMMARY+="**Description:** $BODY\n\n"
          SUMMARY+="---\n"
          SUMMARY+="*This summary was automatically generated. Please review and add any additional context.*"
          
          echo "SUMMARY<<EOF" >> $GITHUB_ENV
          echo "$SUMMARY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment with summary
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "$SUMMARY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUMMARY: ${{ env.SUMMARY }}
